parameters:
  - name: tfpath
    type: string
    default: ''
    values:
      - test
      - test2
stages:
- ${{ if contains(parameters['command'], 'apply') }}:
  - stage: Creating
    displayName: Creating Infrastructure
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - deployment: Build
      displayName: Creating Infrastructure 
      environment: 'apply'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              persistCredentials: true
            - task: AzureKeyVault@2
              inputs:
                azureSubscription: ''
                KeyVaultName: ''
                SecretsFilter: '*'
                RunAsPreJob: true
            
            - template: ./steps/terragrunt.yml

            - task: AzureCLI@2
              displayName:  Creating TF
              inputs:
                azureSubscription: ''
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |-
                  cd $(TF_PATH)

                  #Execução do terragrunt
                  echo "Y" | terragrunt apply-all
              env:
                TF_PATH: ${{parameters.tfpath}}
- ${{ if contains(parameters['command'], 'plan') }}:
  - stage: Planning
    displayName: Planning Infrastructure
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - deployment: Build
      displayName: Planning Infrastructure 
      environment: 'plan'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              persistCredentials: true
            - task: AzureKeyVault@2
              inputs:
                azureSubscription: ''
                KeyVaultName: ''
                SecretsFilter: '*'
                RunAsPreJob: true
            
            - template: ./steps/terragrunt.yml

            - task: AzureCLI@2
              displayName:  Planning TF
              inputs:
                azureSubscription: ''
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |-
                  cd $(TF_PATH)

                  #Execução do terragrunt
                  terragrunt run-all plan
              env:
                TF_PATH: ${{parameters.tfpath}}